/* Study data — ADDITIONAL LEARNING (supplementary, researched; NOT from the original doc) */
var STUDY_CARDS = [
 ["Communication","Communication Process","The path a message travels: Sender → Encode → Message → Channel → Receiver → Decode → Feedback. 'Noise' is any interference that distorts the message."],
 ["Communication","Nonverbal Communication","Messages sent without words — body language, facial expressions, eye contact, gestures, posture, tone. Often outweighs the spoken words when the two conflict."],
 ["Communication","Feedback","The receiver's response that tells the sender whether the message was understood — it closes the communication loop."],
 ["Communication","Modified Block Format","Letter format where the date, complimentary close, and signature begin at the CENTER, while paragraphs stay left-aligned and un-indented. (Full block = everything left-aligned.)"],
 ["Communication","Salutation","The greeting line of a letter (e.g., “Dear Ms. Lee:”). In business letters it is followed by a colon."],
 ["Communication","Complimentary Close","The polite sign-off before the signature (e.g., “Sincerely,”). Only the first word is capitalized."],
 ["Communication","Inside Address","The recipient's name, title, and full address, placed above the salutation in a business letter."],
 ["Communication","Reference Initials","Initials at the bottom of a letter showing who composed vs. typed it (author in CAPS, typist in lowercase: JL/mr)."],
 ["Banking","Blank Endorsement","Just the payee's signature on the back of a check — makes it payable to ANYONE holding it, so it's the least secure."],
 ["Banking","Special (Full) Endorsement","“Pay to the order of [name]” plus your signature — transfers the check to a specific person."],
 ["Banking","Restrictive Endorsement","Limits how a check can be used, e.g., “For Deposit Only” — the most secure endorsement for mailing or depositing."],
 ["Banking","Cashier's Check","A check drawn on and guaranteed by the bank's own funds — more secure than a personal check."],
 ["Banking","Money Order","A prepaid instrument for a set amount, used when a personal check isn't accepted; no bank account required."],
 ["Banking","Deposit Slip","A form listing the cash and checks being added to an account, used to record a deposit."],
 ["Banking","Debit vs Credit (banking)","A debit decreases your account balance (money out); a credit increases it (money in)."],
 ["Banking","Income Statement","Reports revenue and expenses over a PERIOD to show profit or loss (net income). Also called a P&L statement."],
 ["Banking","Statement of Cash Flows","Shows cash moving in and out over a period across operating, investing, and financing activities."],
 ["Banking","Gross Pay vs Net Pay","Gross pay = total earnings before deductions; net pay = take-home pay after taxes and withholdings."],
 ["Tech/Networks","LAN","Local Area Network — connects devices in one location (home, office, school). Fast and relatively secure."],
 ["Tech/Networks","WAN","Wide Area Network — connects devices across large distances/multiple locations. The internet is the largest WAN."],
 ["Tech/Networks","MAN","Metropolitan Area Network — spans a city or campus; larger than a LAN, smaller than a WAN."],
 ["Tech/Networks","RAM vs ROM","RAM = temporary working memory, erased when powered off (volatile). ROM = permanent built-in memory that isn't erased (non-volatile)."],
 ["Tech/Networks","Input vs Output Devices","Input sends data IN (keyboard, mouse, scanner, mic). Output sends data OUT (monitor, printer, speakers)."],
 ["Tech/Networks","CPU","Central Processing Unit — the “brain” of the computer that executes instructions."],
 ["Tech/Networks","Phishing","A scam using fake emails or websites to trick people into revealing passwords or financial information."],
 ["Tech/Networks","Firewall","Hardware or software that blocks unauthorized access to a network while allowing legitimate traffic through."],
 ["Tech/Networks","Cloud Computing","Storing and accessing data and programs over the internet instead of on a local hard drive."],
 ["Tech/Networks","Bit vs Byte","A bit is the smallest unit of data (0 or 1); a byte = 8 bits and typically stores one character."],
 ["Economics","Law of Demand","As price rises, quantity demanded falls (and vice versa) — the demand curve slopes downward."],
 ["Economics","Law of Supply","As price rises, quantity supplied rises — the supply curve slopes upward."],
 ["Economics","Equilibrium Price","The price at which quantity supplied equals quantity demanded; the market “clears.”"],
 ["Economics","Perfect Competition","Many small firms selling identical products with no control over price (e.g., commodity farming)."],
 ["Economics","Monopoly","A single seller controls the entire market with no close substitutes — maximum price control."],
 ["Economics","Oligopoly","A market dominated by a few large firms (e.g., airlines, cell carriers)."],
 ["Economics","Monopolistic Competition","Many firms selling similar but differentiated products (e.g., restaurants, clothing brands)."],
 ["Economics","Opportunity Cost","The value of the next-best alternative given up when you make a choice."],
 ["Economics","Inflation","A sustained rise in the general price level, which reduces purchasing power."],
 ["Economics","Fiscal vs Monetary Policy","Fiscal = government taxing and spending (Congress). Monetary = controlling the money supply and interest rates (the Federal Reserve)."],
 ["Economics","Types of Unemployment","Frictional (between jobs), Structural (skills mismatch), Cyclical (recession), Seasonal (time of year)."],
 ["Economics","GDP vs GNP","GDP = output produced within a country's borders. GNP = output by a country's citizens, wherever located."],
 ["Office/Mgmt","Parliamentary Procedure","Rules (Robert's Rules of Order) for running orderly meetings using motions, seconds, and votes."],
 ["Office/Mgmt","Motion","A formal proposal made in a meeting for the group to take action; must be “seconded” before discussion."],
 ["Office/Mgmt","Span of Control","The number of employees a manager directly supervises. Wide span = flat org; narrow span = tall org."],
 ["Office/Mgmt","Chain of Command","The formal line of authority showing who reports to whom, from top to bottom."],
 ["Office/Mgmt","Delegation","Assigning authority and responsibility for a task to a subordinate while remaining accountable for the outcome."],
 ["Career","Chronological Resume","Lists work history in reverse time order (most recent first) — best for steady, related experience."],
 ["Career","Functional Resume","Organizes by skills rather than dates — good for career changers or those with gaps in work history."],
 ["Career","Cover Letter","A letter accompanying a resume that introduces you and explains why you fit the specific job."],
 ["Career","References","People who can vouch for your work and character; always ask permission before listing them."],
 ["Records","Cross-Reference","A notation placed in a file pointing to where a record is actually stored (when it could be filed under more than one name)."],
 ["Records","Geographic Filing","Arranging records by location (country, state, city) — useful for sales territories."],
 ["Records","Subject Filing","Arranging records by topic or category rather than by name or number."],
];

var STUDY_QUESTIONS = [
 {cat:"Communication", q:"The communication loop is closed when the receiver provides what?",
  opts:["Encoding","Feedback","Noise","A channel"], a:1,
  why:"Feedback is the receiver's response that tells the sender the message was (or wasn't) understood — it closes the loop."},
 {cat:"Communication", q:"When a person's words and emotions conflict, which usually carries more meaning?",
  opts:["The spoken words","Nonverbal communication","The email subject line","The salutation"], a:1,
  why:"Nonverbal cues (body language, tone, expression) tend to override the literal words when the two don't match."},
 {cat:"Communication", q:"In a business letter, the salutation is punctuated with a:",
  opts:["Comma","Colon","Semicolon","Period"], a:1,
  why:"Business-letter salutations end with a colon (e.g., “Dear Ms. Lee:”). A comma is informal/personal."},
 {cat:"Communication", q:"In MODIFIED block format, which elements begin at the center of the page?",
  opts:["Every line","The date, complimentary close, and signature","Only the body paragraphs","The inside address"], a:1,
  why:"Modified block centers the date, close, and signature while paragraphs stay left-aligned. Full block = everything left-aligned."},
 {cat:"Banking", q:"Which endorsement is the MOST secure for mailing a check to be deposited?",
  opts:["Blank endorsement","Special endorsement","Restrictive endorsement (\"For Deposit Only\")","No endorsement"], a:2,
  why:"A restrictive endorsement like “For Deposit Only” limits the check's use, making it safest if lost or stolen."},
 {cat:"Banking", q:"A blank endorsement on a check makes it:",
  opts:["Payable only to a named person","Payable to anyone who holds it","Impossible to cash","A cashier's check"], a:1,
  why:"A blank endorsement is just the payee's signature — it makes the check payable to whoever holds it, so it's the least secure."},
 {cat:"Banking", q:"Which check is drawn on and guaranteed by the bank's own funds?",
  opts:["Personal check","Cashier's check","Post-dated check","Voided check"], a:1,
  why:"A cashier's check is paid from the bank's funds and guaranteed by the bank — more secure than a personal check."},
 {cat:"Banking", q:"Which financial statement reports revenue and expenses over a PERIOD of time?",
  opts:["Balance sheet","Income statement","Deposit slip","Inventory list"], a:1,
  why:"The income statement (P&L) shows revenue minus expenses over a period. The balance sheet is a point-in-time snapshot."},
 {cat:"Banking", q:"Net pay is best defined as:",
  opts:["Total earnings before deductions","Take-home pay after taxes and deductions","Only overtime earnings","Pay before bonuses"], a:1,
  why:"Net pay = gross pay minus taxes and withholdings — the actual take-home amount."},
 {cat:"Tech/Networks", q:"Which network connects devices within a single building or location?",
  opts:["WAN","LAN","MAN","VPN"], a:1,
  why:"A LAN (Local Area Network) covers one location and is fast/secure. A WAN spans large distances."},
 {cat:"Tech/Networks", q:"The internet is the largest example of which type of network?",
  opts:["LAN","PAN","WAN","MAN"], a:2,
  why:"The internet is a WAN (Wide Area Network) — it connects devices across the entire globe."},
 {cat:"Tech/Networks", q:"Which type of memory is VOLATILE (erased when the computer powers off)?",
  opts:["ROM","RAM","The hard drive","A flash drive"], a:1,
  why:"RAM is temporary working memory that's cleared on shutdown. ROM is permanent, non-volatile memory."},
 {cat:"Tech/Networks", q:"A scanner is an example of what kind of device?",
  opts:["Output device","Input device","Storage device","Network device"], a:1,
  why:"A scanner sends data INTO the computer, so it's an input device (like a keyboard or mouse)."},
 {cat:"Tech/Networks", q:"Which security tool blocks unauthorized access to a network?",
  opts:["A firewall","A spreadsheet","An OCR scanner","A router log"], a:0,
  why:"A firewall (hardware or software) blocks unauthorized traffic while allowing legitimate traffic through."},
 {cat:"Tech/Networks", q:"A fraudulent email designed to trick you into giving up your password is called:",
  opts:["Spam","Phishing","Encryption","A macro"], a:1,
  why:"Phishing uses fake emails/sites to steal credentials or financial information."},
 {cat:"Tech/Networks", q:"How many bits are in one byte?",
  opts:["4","8","16","1,024"], a:1,
  why:"A byte = 8 bits, and typically stores a single character."},
 {cat:"Economics", q:"According to the law of demand, when the price of a good rises, quantity demanded:",
  opts:["Rises","Falls","Stays exactly the same","Becomes unlimited"], a:1,
  why:"Law of demand: price and quantity demanded move in opposite directions — the demand curve slopes downward."},
 {cat:"Economics", q:"The price at which quantity supplied equals quantity demanded is called the:",
  opts:["Markup price","Equilibrium price","Break-even price","Retail price"], a:1,
  why:"At the equilibrium price the market clears — supply equals demand."},
 {cat:"Economics", q:"A market with a SINGLE seller and no close substitutes is a:",
  opts:["Oligopoly","Monopoly","Perfect competition","Monopolistic competition"], a:1,
  why:"A monopoly has one seller controlling the whole market — maximum price control."},
 {cat:"Economics", q:"A market dominated by a FEW large firms (e.g., airlines) is a(n):",
  opts:["Monopoly","Oligopoly","Perfect competition","Cooperative"], a:1,
  why:"An oligopoly is dominated by a small number of large firms."},
 {cat:"Economics", q:"Many firms selling similar but differentiated products (restaurants, clothing brands) describes:",
  opts:["Monopoly","Perfect competition","Monopolistic competition","Oligopoly"], a:2,
  why:"Monopolistic competition = many firms with slightly differentiated products."},
 {cat:"Economics", q:"The value of the next-best alternative you give up when making a choice is called:",
  opts:["Sunk cost","Opportunity cost","Variable cost","Fixed cost"], a:1,
  why:"Opportunity cost is what you sacrifice — the next-best option not chosen."},
 {cat:"Economics", q:"Which body sets MONETARY policy in the United States?",
  opts:["Congress","The President","The Federal Reserve","The FTC"], a:2,
  why:"The Federal Reserve controls the money supply and interest rates (monetary policy). Congress handles fiscal policy (taxing/spending)."},
 {cat:"Economics", q:"A worker laid off during a recession is experiencing which type of unemployment?",
  opts:["Frictional","Structural","Cyclical","Seasonal"], a:2,
  why:"Cyclical unemployment is caused by downturns in the business cycle (recessions)."},
 {cat:"Economics", q:"GDP measures the output produced:",
  opts:["By a country's citizens anywhere in the world","Within a country's borders","Only by the government","Only by exporters"], a:1,
  why:"GDP = output within a country's borders. GNP = output by its citizens wherever they are."},
 {cat:"Office/Mgmt", q:"In a formal meeting, a proposal for the group to take action is called a:",
  opts:["Quorum","Motion","Minute","Memo"], a:1,
  why:"A motion is a formal proposal; it must be seconded before the group discusses and votes."},
 {cat:"Office/Mgmt", q:"The number of employees a manager directly supervises is called the:",
  opts:["Chain of command","Span of control","Quorum","Org chart"], a:1,
  why:"Span of control = how many subordinates report directly to one manager. Wide span = flatter organization."},
 {cat:"Office/Mgmt", q:"The set of rules (Robert's Rules of Order) for running orderly meetings is called:",
  opts:["Parliamentary procedure","Due process","Chain of command","Standard operating procedure"], a:0,
  why:"Parliamentary procedure governs motions, seconds, debate, and voting in meetings."},
 {cat:"Career", q:"Which resume type lists work history in reverse time order (most recent first)?",
  opts:["Functional resume","Chronological resume","Combination resume","Reference sheet"], a:1,
  why:"A chronological resume lists jobs newest-to-oldest — best for steady, related experience."},
 {cat:"Career", q:"Which resume is organized by SKILLS and is good for career changers or work gaps?",
  opts:["Chronological resume","Functional resume","Cover letter","Portfolio"], a:1,
  why:"A functional resume emphasizes skills over dates, helping hide gaps or a career switch."},
 {cat:"Records", q:"A notation that points to where a record is actually filed is called a:",
  opts:["Cross-reference","Tickler","Abstract","Index tab"], a:0,
  why:"A cross-reference directs you to the record's real location when it could be filed under more than one name."},
 {cat:"Records", q:"Filing records by country, state, and city is which filing method?",
  opts:["Alphabetic filing","Geographic filing","Numeric filing","Chronological filing"], a:1,
  why:"Geographic filing arranges records by location — useful for sales territories or regional offices."},
];
