/* Study data — ADDITIONAL LEARNING (supplementary, researched; NOT from the original doc) */
var STUDY_CARDS = [
 ["Communication","Communication Process","The path a message travels: Sender → Encode → Message → Channel → Receiver → Decode → Feedback. 'Noise' is any interference that distorts the message."],
 ["Communication","Nonverbal Communication","Messages sent without words — body language, facial expressions, eye contact, gestures, posture, tone. Often outweighs the spoken words when the two conflict."],
 ["Communication","Feedback","The receiver's response that tells the sender whether the message was understood — it closes the communication loop."],
 ["Communication","Modified Block Format","Letter format where the date, complimentary close, and signature begin at the CENTER, while paragraphs stay left-aligned and un-indented. (Full block = everything left-aligned.)"],
 ["Communication","Salutation","The greeting line of a letter (e.g., “Dear Ms. Lee:”). In business letters it is followed by a colon."],
 ["Communication","Complimentary Close","The polite sign-off before the signature (e.g., “Sincerely,”). Only the first word is capitalized."],
 ["Communication","Inside Address","The recipient's name, title, and full address, placed above the salutation in a business letter."],
 ["Communication","Reference Initials","Initials at the bottom of a letter showing who composed vs. typed it (author in CAPS, typist in lowercase: JL/mr)."],
 ["Banking","Blank Endorsement","Just the payee's signature on the back of a check — makes it payable to ANYONE holding it, so it's the least secure."],
 ["Banking","Special (Full) Endorsement","“Pay to the order of [name]” plus your signature — transfers the check to a specific person."],
 ["Banking","Restrictive Endorsement","Limits how a check can be used, e.g., “For Deposit Only” — the most secure endorsement for mailing or depositing."],
 ["Banking","Cashier's Check","A check drawn on and guaranteed by the bank's own funds — more secure than a personal check."],
 ["Banking","Money Order","A prepaid instrument for a set amount, used when a personal check isn't accepted; no bank account required."],
 ["Banking","Deposit Slip","A form listing the cash and checks being added to an account, used to record a deposit."],
 ["Banking","Debit vs Credit (banking)","A debit decreases your account balance (money out); a credit increases it (money in)."],
 ["Banking","Income Statement","Reports revenue and expenses over a PERIOD to show profit or loss (net income). Also called a P&L statement."],
 ["Banking","Statement of Cash Flows","Shows cash moving in and out over a period across operating, investing, and financing activities."],
 ["Banking","Gross Pay vs Net Pay","Gross pay = total earnings before deductions; net pay = take-home pay after taxes and withholdings."],
 ["Tech/Networks","LAN","Local Area Network — connects devices in one location (home, office, school). Fast and relatively secure."],
 ["Tech/Networks","WAN","Wide Area Network — connects devices across large distances/multiple locations. The internet is the largest WAN."],
 ["Tech/Networks","MAN","Metropolitan Area Network — spans a city or campus; larger than a LAN, smaller than a WAN."],
 ["Tech/Networks","RAM vs ROM","RAM = temporary working memory, erased when powered off (volatile). ROM = permanent built-in memory that isn't erased (non-volatile)."],
 ["Tech/Networks","Input vs Output Devices","Input sends data IN (keyboard, mouse, scanner, mic). Output sends data OUT (monitor, printer, speakers)."],
 ["Tech/Networks","CPU","Central Processing Unit — the “brain” of the computer that executes instructions."],
 ["Tech/Networks","Phishing","A scam using fake emails or websites to trick people into revealing passwords or financial information."],
 ["Tech/Networks","Firewall","Hardware or software that blocks unauthorized access to a network while allowing legitimate traffic through."],
 ["Tech/Networks","Cloud Computing","Storing and accessing data and programs over the internet instead of on a local hard drive."],
 ["Tech/Networks","Bit vs Byte","A bit is the smallest unit of data (0 or 1); a byte = 8 bits and typically stores one character."],
 ["Economics","Law of Demand","As price rises, quantity demanded falls (and vice versa) — the demand curve slopes downward."],
 ["Economics","Law of Supply","As price rises, quantity supplied rises — the supply curve slopes upward."],
 ["Economics","Equilibrium Price","The price at which quantity supplied equals quantity demanded; the market “clears.”"],
 ["Economics","Perfect Competition","Many small firms selling identical products with no control over price (e.g., commodity farming)."],
 ["Economics","Monopoly","A single seller controls the entire market with no close substitutes — maximum price control."],
 ["Economics","Oligopoly","A market dominated by a few large firms (e.g., airlines, cell carriers)."],
 ["Economics","Monopolistic Competition","Many firms selling similar but differentiated products (e.g., restaurants, clothing brands)."],
 ["Economics","Opportunity Cost","The value of the next-best alternative given up when you make a choice."],
 ["Economics","Inflation","A sustained rise in the general price level, which reduces purchasing power."],
 ["Economics","Fiscal vs Monetary Policy","Fiscal = government taxing and spending (Congress). Monetary = controlling the money supply and interest rates (the Federal Reserve)."],
 ["Economics","Types of Unemployment","Frictional (between jobs), Structural (skills mismatch), Cyclical (recession), Seasonal (time of year)."],
 ["Economics","GDP vs GNP","GDP = output produced within a country's borders. GNP = output by a country's citizens, wherever located."],
 ["Office/Mgmt","Parliamentary Procedure","Rules (Robert's Rules of Order) for running orderly meetings using motions, seconds, and votes."],
 ["Office/Mgmt","Motion","A formal proposal made in a meeting for the group to take action; must be “seconded” before discussion."],
 ["Office/Mgmt","Span of Control","The number of employees a manager directly supervises. Wide span = flat org; narrow span = tall org."],
 ["Office/Mgmt","Chain of Command","The formal line of authority showing who reports to whom, from top to bottom."],
 ["Office/Mgmt","Delegation","Assigning authority and responsibility for a task to a subordinate while remaining accountable for the outcome."],
 ["Career","Chronological Resume","Lists work history in reverse time order (most recent first) — best for steady, related experience."],
 ["Career","Functional Resume","Organizes by skills rather than dates — good for career changers or those with gaps in work history."],
 ["Career","Cover Letter","A letter accompanying a resume that introduces you and explains why you fit the specific job."],
 ["Career","References","People who can vouch for your work and character; always ask permission before listing them."],
 ["Records","Cross-Reference","A notation placed in a file pointing to where a record is actually stored (when it could be filed under more than one name)."],
 ["Records","Geographic Filing","Arranging records by location (country, state, city) — useful for sales territories."],
 ["Records","Subject Filing","Arranging records by topic or category rather than by name or number."],
 /* ---- Deeper dives on the newly-added topics (training, feedback, data-viz, dress, meetings) ---- */
 ["HR/Training","ADDIE Model","Instructional-design framework for building training: Analyze → Design → Develop → Implement → Evaluate. (Kirkpatrick evaluates training; ADDIE builds it.)"],
 ["HR/Training","Kirkpatrick — 4 Levels","Evaluates training in order: 1) Reaction (did they like it?) 2) Learning (did they gain knowledge/skills?) 3) Behavior (are they applying it on the job?) 4) Results (did it improve business outcomes?)."],
 ["HR/Training","360-Degree Feedback","Performance feedback collected from multiple sources around an employee — peers, subordinates, managers, and self — for a well-rounded view."],
 ["HR/Training","Orientation vs Onboarding","Orientation is the short initial welcome (paperwork, tour, intros). Onboarding is the longer process of fully integrating and ramping a new hire over weeks/months."],
 ["HR/Training","Mentoring vs Coaching","Mentoring is a longer-term relationship guiding overall career growth. Coaching is shorter-term and focused on improving a specific skill or performance gap."],
 ["HR/Training","Maslow's Hierarchy of Needs","Motivation theory: needs are met bottom-up — Physiological → Safety → Social/Belonging → Esteem → Self-Actualization."],
 ["HR/Training","Herzberg's Two-Factor Theory","Hygiene factors (salary, job security, conditions) only prevent dissatisfaction; motivators (recognition, growth, achievement) are what actually drive satisfaction."],
 ["HR/Training","McGregor's Theory X / Theory Y","Theory X assumes employees dislike work and need close control; Theory Y assumes they're self-motivated and thrive with responsibility."],
 ["Data & Charts","Histogram","Shows the distribution/frequency of ONE continuous variable grouped into bins. Different from a bar chart, which compares discrete categories."],
 ["Data & Charts","Gantt Chart","Horizontal bars mapping project tasks against a timeline — shows schedule, duration, and dependencies."],
 ["Data & Charts","Area Chart","Like a line chart with the space below filled in — emphasizes the magnitude/volume of a trend over time."],
 ["Data & Charts","Combo Chart","Combines two chart types (e.g., bars + a line) to display related data on different scales in one view."],
 ["Data & Charts","Truncated Axis","When a chart's value axis doesn't start at zero, small differences look huge — a common way charts mislead. Always check the scale before drawing conclusions."],
 ["Data & Charts","Data-Ink Ratio","Tufte's principle: maximize the ink that conveys real data and remove 'chartjunk' (heavy gridlines, 3-D effects, decoration)."],
 ["Office/Mgmt","Dress Code Hierarchy","From most to least formal: Business Formal → Business Professional → Business Casual → Casual. Match the level to the industry and occasion (client meeting vs. ordinary day)."],
 ["Office/Mgmt","Smart Casual","A step above business casual: polished, put-together pieces (e.g., blazer with dark jeans) — neat but not suited-up."],
 ["Office/Mgmt","Visitor Badge & Sign-In Log","A security control: visitors sign in, receive a badge, and are escorted. Creates an audit trail and supports building safety."],
 ["Office/Mgmt","Meeting Types","Common formats: informational (share updates), decision-making (reach a choice), brainstorming (generate ideas), status/stand-up (quick progress check), and one-on-one."],
 ["Communication","Mehrabian's 7-38-55 Rule","When a speaker's words and feelings conflict, listeners take ~7% of the meaning from words, 38% from tone of voice, and 55% from body language — so nonverbal cues dominate emotional messages."],
 ["Communication","Active vs Passive Voice","Active voice ('The team met the goal') is clearer and more direct than passive ('The goal was met') — preferred in most business writing."],
 /* ---- Deeper dives on the newest topics: security, compliance, hiring/HR ---- */
 ["Security & Compliance","CIA Triad","The core model of information security: Confidentiality (limit access), Integrity (keep data accurate/untampered), and Availability (keep it accessible when needed)."],
 ["Security & Compliance","Zero Trust","A security model summarized as 'never trust, always verify' — every user and device must be authenticated and authorized, even inside the network."],
 ["Security & Compliance","Phishing → Spear Phishing → Whaling","Phishing casts a wide net; spear phishing targets a specific person; whaling targets a senior executive ('big fish'). More targeting = more convincing."],
 ["Security & Compliance","Symmetric vs Asymmetric Encryption","Symmetric uses ONE shared secret key (fast). Asymmetric uses a public/private KEY PAIR (you encrypt with the public key, decrypt with the private)."],
 ["Security & Compliance","GDPR vs CCPA","GDPR is the EU's data-privacy law; CCPA is California's. Both give individuals rights over how their personal data is collected and used."],
 ["Security & Compliance","Incident Response (PICERL)","The lifecycle for handling a breach: Prepare → Identify → Contain → Eradicate → Recover → Lessons learned."],
 ["Security & Compliance","Penetration Test vs Vulnerability Scan","A vulnerability scan automatically lists known weaknesses; a penetration test has experts actively try to exploit them, like a real attacker."],
 ["Security & Compliance","Whistleblower Protection","Laws like Sarbanes-Oxley shield employees who report fraud or violations from workplace retaliation."],
 ["Security & Compliance","Defense in Depth","Layering multiple, overlapping security controls (firewall + MFA + encryption + training) so no single failure exposes the system."],
 ["HR/Training","SMART vs OKRs","SMART defines one well-formed goal (Specific, Measurable, Achievable, Relevant, Time-bound). OKRs pair an ambitious Objective with 3–5 measurable Key Results."],
 ["HR/Training","9-Box Grid","A talent-review matrix plotting employees on performance (x) vs. potential (y) to guide development and succession decisions."],
 ["HR/Training","Progressive Discipline","Escalating response to performance/conduct issues: verbal warning → written warning → suspension → termination, documented at each step."],
 ["Career","STAR Method","A way to answer behavioral interview questions: describe the Situation, the Task, the Action you took, and the Result you achieved."],
 ["Career","Hard vs Soft Skills","Hard skills are teachable/technical (Excel, accounting); soft skills are interpersonal (communication, teamwork). Employers want both."],
 ["Career","Transferable Skills","Skills that carry across roles and industries (writing, problem-solving, project management) — key when changing careers or explaining gaps."],
];

var STUDY_QUESTIONS = [
 {cat:"Communication", q:"The communication loop is closed when the receiver provides what?",
  opts:["Encoding","Feedback","Noise","A channel"], a:1,
  why:"Feedback is the receiver's response that tells the sender the message was (or wasn't) understood — it closes the loop."},
 {cat:"Communication", q:"When a person's words and emotions conflict, which usually carries more meaning?",
  opts:["The spoken words","Nonverbal communication","The email subject line","The salutation"], a:1,
  why:"Nonverbal cues (body language, tone, expression) tend to override the literal words when the two don't match."},
 {cat:"Communication", q:"In a business letter, the salutation is punctuated with a:",
  opts:["Comma","Colon","Semicolon","Period"], a:1,
  why:"Business-letter salutations end with a colon (e.g., “Dear Ms. Lee:”). A comma is informal/personal."},
 {cat:"Communication", q:"In MODIFIED block format, which elements begin at the center of the page?",
  opts:["Every line","The date, complimentary close, and signature","Only the body paragraphs","The inside address"], a:1,
  why:"Modified block centers the date, close, and signature while paragraphs stay left-aligned. Full block = everything left-aligned."},
 {cat:"Banking", q:"Which endorsement is the MOST secure for mailing a check to be deposited?",
  opts:["Blank endorsement","Special endorsement","Restrictive endorsement (\"For Deposit Only\")","No endorsement"], a:2,
  why:"A restrictive endorsement like “For Deposit Only” limits the check's use, making it safest if lost or stolen."},
 {cat:"Banking", q:"A blank endorsement on a check makes it:",
  opts:["Payable only to a named person","Payable to anyone who holds it","Impossible to cash","A cashier's check"], a:1,
  why:"A blank endorsement is just the payee's signature — it makes the check payable to whoever holds it, so it's the least secure."},
 {cat:"Banking", q:"Which check is drawn on and guaranteed by the bank's own funds?",
  opts:["Personal check","Cashier's check","Post-dated check","Voided check"], a:1,
  why:"A cashier's check is paid from the bank's funds and guaranteed by the bank — more secure than a personal check."},
 {cat:"Banking", q:"Which financial statement reports revenue and expenses over a PERIOD of time?",
  opts:["Balance sheet","Income statement","Deposit slip","Inventory list"], a:1,
  why:"The income statement (P&L) shows revenue minus expenses over a period. The balance sheet is a point-in-time snapshot."},
 {cat:"Banking", q:"Net pay is best defined as:",
  opts:["Total earnings before deductions","Take-home pay after taxes and deductions","Only overtime earnings","Pay before bonuses"], a:1,
  why:"Net pay = gross pay minus taxes and withholdings — the actual take-home amount."},
 {cat:"Tech/Networks", q:"Which network connects devices within a single building or location?",
  opts:["WAN","LAN","MAN","VPN"], a:1,
  why:"A LAN (Local Area Network) covers one location and is fast/secure. A WAN spans large distances."},
 {cat:"Tech/Networks", q:"The internet is the largest example of which type of network?",
  opts:["LAN","PAN","WAN","MAN"], a:2,
  why:"The internet is a WAN (Wide Area Network) — it connects devices across the entire globe."},
 {cat:"Tech/Networks", q:"Which type of memory is VOLATILE (erased when the computer powers off)?",
  opts:["ROM","RAM","The hard drive","A flash drive"], a:1,
  why:"RAM is temporary working memory that's cleared on shutdown. ROM is permanent, non-volatile memory."},
 {cat:"Tech/Networks", q:"A scanner is an example of what kind of device?",
  opts:["Output device","Input device","Storage device","Network device"], a:1,
  why:"A scanner sends data INTO the computer, so it's an input device (like a keyboard or mouse)."},
 {cat:"Tech/Networks", q:"Which security tool blocks unauthorized access to a network?",
  opts:["A firewall","A spreadsheet","An OCR scanner","A router log"], a:0,
  why:"A firewall (hardware or software) blocks unauthorized traffic while allowing legitimate traffic through."},
 {cat:"Tech/Networks", q:"A fraudulent email designed to trick you into giving up your password is called:",
  opts:["Spam","Phishing","Encryption","A macro"], a:1,
  why:"Phishing uses fake emails/sites to steal credentials or financial information."},
 {cat:"Tech/Networks", q:"How many bits are in one byte?",
  opts:["4","8","16","1,024"], a:1,
  why:"A byte = 8 bits, and typically stores a single character."},
 {cat:"Economics", q:"According to the law of demand, when the price of a good rises, quantity demanded:",
  opts:["Rises","Falls","Stays exactly the same","Becomes unlimited"], a:1,
  why:"Law of demand: price and quantity demanded move in opposite directions — the demand curve slopes downward."},
 {cat:"Economics", q:"The price at which quantity supplied equals quantity demanded is called the:",
  opts:["Markup price","Equilibrium price","Break-even price","Retail price"], a:1,
  why:"At the equilibrium price the market clears — supply equals demand."},
 {cat:"Economics", q:"A market with a SINGLE seller and no close substitutes is a:",
  opts:["Oligopoly","Monopoly","Perfect competition","Monopolistic competition"], a:1,
  why:"A monopoly has one seller controlling the whole market — maximum price control."},
 {cat:"Economics", q:"A market dominated by a FEW large firms (e.g., airlines) is a(n):",
  opts:["Monopoly","Oligopoly","Perfect competition","Cooperative"], a:1,
  why:"An oligopoly is dominated by a small number of large firms."},
 {cat:"Economics", q:"Many firms selling similar but differentiated products (restaurants, clothing brands) describes:",
  opts:["Monopoly","Perfect competition","Monopolistic competition","Oligopoly"], a:2,
  why:"Monopolistic competition = many firms with slightly differentiated products."},
 {cat:"Economics", q:"The value of the next-best alternative you give up when making a choice is called:",
  opts:["Sunk cost","Opportunity cost","Variable cost","Fixed cost"], a:1,
  why:"Opportunity cost is what you sacrifice — the next-best option not chosen."},
 {cat:"Economics", q:"Which body sets MONETARY policy in the United States?",
  opts:["Congress","The President","The Federal Reserve","The FTC"], a:2,
  why:"The Federal Reserve controls the money supply and interest rates (monetary policy). Congress handles fiscal policy (taxing/spending)."},
 {cat:"Economics", q:"A worker laid off during a recession is experiencing which type of unemployment?",
  opts:["Frictional","Structural","Cyclical","Seasonal"], a:2,
  why:"Cyclical unemployment is caused by downturns in the business cycle (recessions)."},
 {cat:"Economics", q:"GDP measures the output produced:",
  opts:["By a country's citizens anywhere in the world","Within a country's borders","Only by the government","Only by exporters"], a:1,
  why:"GDP = output within a country's borders. GNP = output by its citizens wherever they are."},
 {cat:"Office/Mgmt", q:"In a formal meeting, a proposal for the group to take action is called a:",
  opts:["Quorum","Motion","Minute","Memo"], a:1,
  why:"A motion is a formal proposal; it must be seconded before the group discusses and votes."},
 {cat:"Office/Mgmt", q:"The number of employees a manager directly supervises is called the:",
  opts:["Chain of command","Span of control","Quorum","Org chart"], a:1,
  why:"Span of control = how many subordinates report directly to one manager. Wide span = flatter organization."},
 {cat:"Office/Mgmt", q:"The set of rules (Robert's Rules of Order) for running orderly meetings is called:",
  opts:["Parliamentary procedure","Due process","Chain of command","Standard operating procedure"], a:0,
  why:"Parliamentary procedure governs motions, seconds, debate, and voting in meetings."},
 {cat:"Career", q:"Which resume type lists work history in reverse time order (most recent first)?",
  opts:["Functional resume","Chronological resume","Combination resume","Reference sheet"], a:1,
  why:"A chronological resume lists jobs newest-to-oldest — best for steady, related experience."},
 {cat:"Career", q:"Which resume is organized by SKILLS and is good for career changers or work gaps?",
  opts:["Chronological resume","Functional resume","Cover letter","Portfolio"], a:1,
  why:"A functional resume emphasizes skills over dates, helping hide gaps or a career switch."},
 {cat:"Records", q:"A notation that points to where a record is actually filed is called a:",
  opts:["Cross-reference","Tickler","Abstract","Index tab"], a:0,
  why:"A cross-reference directs you to the record's real location when it could be filed under more than one name."},
 {cat:"Records", q:"Filing records by country, state, and city is which filing method?",
  opts:["Alphabetic filing","Geographic filing","Numeric filing","Chronological filing"], a:1,
  why:"Geographic filing arranges records by location — useful for sales territories or regional offices."},
 /* ---- Deeper dives on the newly-added topics ---- */
 {cat:"HR/Training", q:"The ADDIE instructional-design model stands for:",
  opts:["Analyze, Design, Develop, Implement, Evaluate","Assess, Deliver, Demo, Inspect, Export","Acquire, Define, Decide, Improve, Execute","Align, Develop, Document, Iterate, Evaluate"], a:0,
  why:"ADDIE = Analyze → Design → Develop → Implement → Evaluate. It builds training; Kirkpatrick evaluates it."},
 {cat:"HR/Training", q:"Which is the FIRST level of the Kirkpatrick training-evaluation model?",
  opts:["Results","Behavior","Reaction","Learning"], a:2,
  why:"Order is Reaction → Learning → Behavior → Results. Level 1 measures the learners' immediate reaction."},
 {cat:"HR/Training", q:"360-degree feedback gathers performance input from:",
  opts:["Only the direct manager","Only the employee (self-review)","Peers, subordinates, managers, and self","An outside consultant only"], a:2,
  why:"360-degree feedback collects views from all around the employee — peers, reports, managers, and self."},
 {cat:"HR/Training", q:"In Herzberg's Two-Factor Theory, salary and job security are:",
  opts:["Motivators that drive satisfaction","Hygiene factors that prevent dissatisfaction","Self-actualization needs","Irrelevant to motivation"], a:1,
  why:"Hygiene factors (pay, security, conditions) only prevent dissatisfaction; motivators like recognition and growth drive satisfaction."},
 {cat:"HR/Training", q:"McGregor's Theory Y assumes that employees:",
  opts:["Dislike work and need close supervision","Are self-motivated and thrive with responsibility","Only work for money","Cannot be trained"], a:1,
  why:"Theory Y assumes employees are self-motivated and do their best with autonomy; Theory X assumes the opposite."},
 {cat:"HR/Training", q:"Orientation differs from onboarding in that orientation is:",
  opts:["The long, multi-week integration process","The short initial welcome (paperwork, tour, intros)","A type of performance review","Only for managers"], a:1,
  why:"Orientation is the brief first-day welcome; onboarding is the longer process of fully ramping a new hire."},
 {cat:"Data & Charts", q:"Which chart shows the distribution of a single CONTINUOUS variable?",
  opts:["Bar chart","Histogram","Pie chart","Gantt chart"], a:1,
  why:"A histogram bins a continuous variable to show its distribution. A bar chart compares discrete categories."},
 {cat:"Data & Charts", q:"Which chart maps project tasks against a timeline to show schedule and dependencies?",
  opts:["Scatter plot","Gantt chart","Pie chart","Area chart"], a:1,
  why:"A Gantt chart uses horizontal bars along a timeline to show task durations and dependencies."},
 {cat:"Data & Charts", q:"A chart whose value axis starts above zero can:",
  opts:["Make the data more accurate","Exaggerate differences and mislead the reader","Only be used for pie charts","Improve the data-ink ratio"], a:1,
  why:"A truncated (non-zero) axis makes small differences look large — always check the scale before concluding."},
 {cat:"Data & Charts", q:"Tufte's 'data-ink ratio' principle says you should:",
  opts:["Add 3-D effects and gridlines for emphasis","Maximize data-conveying ink and remove chartjunk","Use as many colors as possible","Always start with a pie chart"], a:1,
  why:"Maximize the ink that conveys real data and strip decoration (3-D, heavy gridlines, clutter)."},
 {cat:"Communication", q:"By Mehrabian's 7-38-55 rule, when words and feelings conflict, most meaning comes from:",
  opts:["The exact words (7%)","Tone of voice (38%)","Body language (55%)","The email subject line"], a:2,
  why:"For emotionally charged messages, ~55% of meaning is body language, 38% tone, and only 7% the literal words."},
 {cat:"Office/Mgmt", q:"Which dress code is one step LESS formal than Business Professional?",
  opts:["Business Formal","Business Casual","Black Tie","Athleisure"], a:1,
  why:"From most to least formal: Business Formal → Business Professional → Business Casual → Casual."},
 /* ---- Deeper dives on the newest topics: security, compliance, hiring/HR ---- */
 {cat:"Security & Compliance", q:"The CIA triad in information security stands for:",
  opts:["Central, Internal, Access","Confidentiality, Integrity, Availability","Control, Identity, Authorization","Cyber, Internet, Authentication"], a:1,
  why:"CIA = Confidentiality (limit access), Integrity (keep data accurate), Availability (keep it accessible)."},
 {cat:"Security & Compliance", q:"'Never trust, always verify' best describes which security model?",
  opts:["Defense in depth","Zero Trust","Least privilege","Open access"], a:1,
  why:"Zero Trust authenticates and authorizes every user/device, even inside the network."},
 {cat:"Security & Compliance", q:"A highly targeted phishing attack aimed at a senior executive is called:",
  opts:["Spam","Spear phishing","Whaling","Pharming"], a:2,
  why:"Whaling targets a 'big fish' executive. Spear phishing targets a specific person; plain phishing is mass-sent."},
 {cat:"Security & Compliance", q:"Which encryption uses a public/private KEY PAIR?",
  opts:["Symmetric","Asymmetric","Hashing","None — keys are never paired"], a:1,
  why:"Asymmetric encryption uses a public key to encrypt and a private key to decrypt. Symmetric uses one shared key."},
 {cat:"Security & Compliance", q:"GDPR is the data-privacy law of which jurisdiction?",
  opts:["California","The European Union","Canada","Japan"], a:1,
  why:"GDPR governs the EU; California's equivalent is the CCPA."},
 {cat:"Career", q:"The STAR method structures a behavioral interview answer as:",
  opts:["Skills, Training, Awards, References","Situation, Task, Action, Result","Strengths, Threats, Aims, Roles","Start, Try, Adjust, Repeat"], a:1,
  why:"STAR = Situation → Task → Action → Result: set the scene, your responsibility, what you did, and the outcome."},
 {cat:"HR/Training", q:"A 9-box grid plots employees on which two axes?",
  opts:["Salary vs tenure","Performance vs potential","Age vs experience","Attendance vs output"], a:1,
  why:"The 9-box talent matrix maps current performance against future potential to guide development and succession."},
 {cat:"HR/Training", q:"Progressive discipline typically begins with:",
  opts:["Immediate termination","A verbal warning","Suspension without pay","A demotion"], a:1,
  why:"It escalates: verbal warning → written warning → suspension → termination, documented at each step."},
];
