/* Study data — FROM YOUR NOTES (the recorded doc) */
var STUDY_CARDS = [
 // Communication & Documents
 ["Comm/Docs","Memo (Memorandum)","A brief, INTERNAL document used to share information, updates, or directives within an organization. Contrast with letters, which are EXTERNAL."],
 ["Comm/Docs","Block Format","Standard business letter format: all text left-aligned, single-spaced paragraphs, double space between paragraphs, no indentation."],
 ["Comm/Docs","Letterhead","Professionally designed heading at the top of stationery featuring company name, logo, address, and contact details."],
 ["Comm/Docs","Stationery","Branded writing materials and office supplies used for official communication and branding."],
 ["Comm/Docs","Agenda","A list of topics or items to be discussed at a meeting, distributed to attendees beforehand."],
 ["Comm/Docs","Minutes","The official written record of what was discussed and decided at a meeting (attendees, date, agenda, decisions, action items)."],
 ["Comm/Docs","Internal Signature","Identifies the sender within the company WITHOUT the company name. Used for documents sent within the organization."],
 ["Comm/Docs","Enclosure vs Copy Notation","Enclosure tells the reader extra documents are included; Copy notation tells them who else received the letter (like cc)."],
 ["Comm/Docs","Business Letter 5 C's","Clear, Concise, Courteous, Complete, Correct."],
 ["Comm/Docs","Colloquial Language","Informal words/phrases used in ordinary conversation. NOT appropriate for professional business writing."],
 ["Comm/Docs","Second-Page Heading Rule","On page 2+ of a letter/memo, the heading must include the addressee name, page number, and date."],
 ["Comm/Docs","Proofreading","Checking documents for accuracy in content, grammar, spelling, and punctuation — always the final step before distributing."],

 // Mail
 ["Mail","Express Mail","Fastest USPS service: overnight / 1-day delivery. Most expensive."],
 ["Mail","Priority Mail","USPS service delivering in 1–3 business days. Middle ground between Express and First-Class."],
 ["Mail","First-Class Mail","Standard mail for letters, bills, and correspondence. 1–5 business days, up to 13 oz."],
 ["Mail","Parcel Post","USPS service for large, heavy, non-letter packages. 2–8 days. Cheapest for heavy items."],
 ["Mail","Certified Mail","Provides proof of mailing and delivery confirmation (signature). Same speed as First-Class. Used for legal documents."],
 ["Mail","Registered Mail","Maximum-security USPS service: tracked at every step and insured. For valuables."],
 ["Mail","Mail Speed Ranking","Express (1 day) > Priority (1–3) > First-Class (1–5) > Parcel Post (2–8)."],

 // Ownership
 ["Ownership","Sole Proprietorship","Owned by one person. Easiest to start. Owner has UNLIMITED personal liability — personal and business assets are legally the same. Pass-through taxation."],
 ["Ownership","Partnership","Owned by 2+ people. General partners have unlimited liability; limited partners are liable only up to their investment. Pass-through taxation."],
 ["Ownership","LLC (Limited Liability Company)","Offers limited liability protection WITH pass-through taxation. Easier than a corporation, more protection than a partnership."],
 ["Ownership","C Corporation","A separate legal entity from owners (shareholders). Strongest liability protection, can raise capital via stock, perpetual existence — but faces DOUBLE taxation."],
 ["Ownership","S Corporation","A corporation structured to AVOID double taxation; profits/losses pass to personal income. Must file with the IRS and meet limits (≤100 shareholders, no non-resident aliens)."],
 ["Ownership","Cooperative","Owned and operated for the benefit of its members (user-owners), who share profits. # of shares does NOT equal voting power."],
 ["Ownership","Franchise","A contractual agreement to use the name and sell the products/services of a company in a designated geographic area."],
 ["Ownership","Nonprofit / 501(c)(3)","Does public or religious work; cannot distribute profits to members or political campaigns. Must get tax-exempt status from the IRS."],
 ["Ownership","Limited Liability","Owners are only liable up to the amount they invested. Protects personal assets."],
 ["Ownership","DBA (Doing Business As)","A trade/fictitious name. Gives NO legal protection but may be legally required to operate under a name different from your legal name."],

 // Finance & Accounting
 ["Finance","Balance Sheet","A financial snapshot at a point in time: Assets = Liabilities + Owner's Equity."],
 ["Finance","Net Income","Revenue minus ALL expenses — the 'bottom line.'"],
 ["Finance","Gross Profit","Revenue minus Cost of Goods Sold."],
 ["Finance","Accounts Payable","Money a company OWES to suppliers/vendors for goods received but not yet paid for. A liability."],
 ["Finance","Accounts Receivable","Money OWED TO a company by its customers for credit sales. A current asset."],
 ["Finance","Liabilities","Creditors' claims to the assets of a business — what the company owes."],
 ["Finance","Owner's Equity","An owner's claim to the assets of a business. Assets minus Liabilities."],
 ["Finance","Working Capital","Current Assets minus Current Liabilities. Measures short-term liquidity/health."],
 ["Finance","Current Assets","Assets expected to be used or converted to cash within one year (cash, inventory, accounts receivable)."],
 ["Finance","Fixed Assets","Long-term assets providing benefits for more than one year (building, land, machinery)."],
 ["Finance","Petty Cash","A small fund kept on hand for minor incidental office expenses. Always documented with receipts."],
 ["Finance","Imprest System","A FIXED petty cash fund that is replenished back to its original set amount after expenditures (start $200, spend $150, replenish $150)."],
 ["Finance","Voucher","A document that authorizes payment to a vendor AFTER confirming goods/services were received."],
 ["Finance","Three-Way Match","Matching three documents before authorizing vendor payment: (1) Purchase Order, (2) Receiving Report, (3) Vendor Invoice."],
 ["Finance","Purchase Requisition","An INTERNAL document requesting permission to buy something — goes to purchasing for approval BEFORE a Purchase Order is issued."],
 ["Finance","Bank Reconciliation","Comparing a company's book records with the bank's statement; adjusts for outstanding checks, deposits in transit, fees, and errors."],
 ["Finance","Compound Interest","Interest calculated on your principal PLUS previously earned interest — interest is added to the balance, then the next period earns on the new total."],
 ["Finance","GAAP","Generally Accepted Accounting Principles — the standard rules for financial reporting in the U.S."],
 ["Finance","Journal (Accounting)","The first book of entry where daily transactions are recorded chronologically before posting to the ledger. Provides an audit trail."],
 ["Finance","W-2 Form","The tax form an employer sends each employee and the IRS at year-end, reporting annual wages and taxes withheld."],

 // Management & Leadership
 ["Management","4 Functions of Management (POLC)","Planning, Organizing, Leading/Directing, Controlling."],
 ["Management","3 Levels of Management","Executive/Top (CEO — vision/strategy), Middle (department heads — implement strategy), Line/Supervisory (team leads — day-to-day)."],
 ["Management","Line Authority","Direct chain of command — a manager's direct authority over subordinates."],
 ["Management","Staff Authority","Advisory authority only — provides expertise/recommendations, no direct command."],
 ["Management","Functional Authority","A specialist's authority across departments for a specific function."],
 ["Management","Laissez-Faire Leadership","'Hands-off' style — the leader gives team members freedom with minimal direction. Best with skilled, self-motivated teams."],
 ["Management","Autocratic Leadership","The leader makes decisions alone without consulting subordinates."],
 ["Management","Democratic Leadership","The leader collaborates and seeks team input before deciding."],
 ["Management","Transformational Leadership","Focuses on inspiring and motivating employees to innovate and exceed expectations."],
 ["Management","Servant Leadership","Focuses on the growth, needs, and well-being of team members, often over the leader's own."],
 ["Management","SWOT Analysis","Strengths, Weaknesses, Opportunities, Threats — a strategic planning tool for evaluating an organization's position."],
 ["Management","Eisenhower Matrix","Prioritizes tasks in 4 quadrants: Do First (urgent+important), Schedule (important, not urgent), Delegate (urgent, not important), Eliminate (neither)."],
 ["Management","SMART Goals","Specific, Measurable, Achievable, Relevant, Time-bound."],
 ["Management","Organizational Chart","A visual hierarchy showing reporting relationships. Solid lines = direct authority; dashed lines = functional/secondary relationships."],
 ["Management","Vision vs Mission","Vision = future aspiration ('what we want to become'). Mission = present purpose ('what we do and how')."],
 ["Management","Operations Management","Overseeing day-to-day processes (shipping, manufacturing, quality) to keep them running smoothly."],
 ["Management","Quorum","The minimum number of people that must be present to conduct business at a meeting."],
 ["Management","Pareto Principle (80/20)","Roughly 80% of results come from 20% of the tasks — tackle that vital 20% first."],

 // Economics
 ["Economics","Capitalism","An economic system where private individuals own and operate the majority of businesses."],
 ["Economics","Socialism","An economic system where the government owns the means of production."],
 ["Economics","Communism","An economic system where the factors of production are owned and directed by the state."],
 ["Economics","Microeconomics","The study of individual and business-level economic decisions."],
 ["Economics","Macroeconomics","The study of how the whole/aggregate economy behaves: inflation, GDP, price levels, unemployment."],
 ["Economics","GDP","Gross Domestic Product — the total market value of all goods and services produced within a country in a given period."],
 ["Economics","Scarcity","The fundamental economic problem: unlimited wants vs. limited resources."],
 ["Economics","Factors of Production","Land, Labor, and Capital."],
 ["Economics","Cartel vs Trust","A cartel is companies COLLUDING while keeping autonomy (easy to leave). A trust is companies MERGING under trustees (hard to leave)."],
 ["Economics","Antitrust Laws","Laws that promote competition and prevent monopolies. Enforced by the FTC."],
 ["Economics","FTC","Federal Trade Commission — enforces antitrust laws, handles consumer complaints, promotes competition."],
 ["Economics","Business Cycle Stages","Expansion → Peak/Boom → Contraction/Recession → Trough/Depression, then repeats."],

 // Technology & Info Processing
 ["Technology","Modem vs Router","A modem connects the home/office TO the internet (via an ISP). A router connects devices WITHIN the local network (LAN)."],
 ["Technology","Operating System (OS)","Software that controls computer operations, maintains files, runs applications, and manages hardware devices."],
 ["Technology","Hardware vs Software","Hardware = physical components (monitor, printer, motherboard). Software = the programs and operating information."],
 ["Technology","Server","A computer that stores data and application software for all workstations in a building or network."],
 ["Technology","Intranet","An organization's internal communications network for employees only — not public."],
 ["Technology","OCR","Optical Character Recognition — turns scanned PDFs and images into editable text."],
 ["Technology","Primary Key","A unique identifier for each record in a database table (e.g., Customer ID). Cannot be null; no duplicates."],
 ["Technology","Foreign Key","A field that links tables together. CAN be null and there can be multiple."],
 ["Technology","Relational Database","A database that understands relationships between lists/tables, connected by keys."],
 ["Technology","PDF","Portable Document Format — preserves layout and embedded fonts across ALL devices. Best for a final, fixed-layout document."],
 ["Technology","Information Processing Cycle","Input → Processing → Output → Storage."],
 ["Technology","Batch vs Real-Time Processing","Batch = grouped data processed at intervals (monthly payroll). Real-time = processed instantly as it occurs (e-commerce inventory)."],
 ["Technology","Data Mining","Extracting and finding significant patterns in large datasets using software."],
 ["Technology","SELECT Query","Retrieves data without changing it — the most common query. Components: SELECT, FROM, WHERE, ORDER BY."],

 // Filing & Records
 ["Records","Tickler File","A date-based reminder system using 31 daily folders + 12 monthly folders to 'tickle' your memory about upcoming deadlines."],
 ["Records","Retention Schedule","A schedule showing how long types of records must be kept before destruction. Default to the longest applicable period; stop destroying during a legal hold."],
 ["Records","Records Lifecycle","Creation → Maintenance/Use → Disposition (destruction or archive)."],
 ["Records","ARMA Filing Rules","Index unit-by-unit; case doesn't matter; 'nothing comes before something'; remove punctuation; numbers file before letters; file last name first."],
 ["Records","Chronological Filing","Files stored by date. Using YYYY-MM-DD naming makes them sort automatically."],
 ["Records","5 Steps of Filing","Inspecting → Indexing → Coding → Sorting → Storing."],
 ["Records","Microfiche","A microfilm storage medium with tiny photographic images of documents on small sheets of film — old-school archival tech."],
 ["Records","3-2-1 Rule","For record storage: 3 copies, 2 different formats, 1 offsite."],

 // Ethics, Safety, Law, Career
 ["Ethics/Law","Sarbanes-Oxley Act (SOX)","A 2002 federal law requiring CEOs/CFOs to approve financial statements (criminally liable), mandating annual audits, and protecting whistleblowers. Goal: protect investors."],
 ["Ethics/Law","ADA","Americans with Disabilities Act — employers (15+ employees) must provide accommodations and equal opportunity; public places/services must be accessible."],
 ["Ethics/Law","FLSA","Fair Labor Standards Act — mandates 1.5× overtime pay, recordkeeping, federal minimum wage, and child-labor restrictions. Enforced by the Dept. of Labor."],
 ["Ethics/Law","EEOC","Equal Employment Opportunity Commission — prohibits employment discrimination based on age, gender, race, national origin, etc."],
 ["Ethics/Law","HIPAA","Protects specific health information from being disclosed without patient consent."],
 ["Ethics/Law","Ergonomics","The study of designing workstations/equipment to minimize strain and injury. Monitor at eye level, feet flat, wrists neutral, lower back supported."],
 ["Ethics/Law","Confidentiality","Protecting sensitive information from unauthorized access — lock screens, secure documents, follow privacy policies."],
 ["Ethics/Law","Least Privilege","Granting access to information only up to what is necessary for someone's role."],
 ["Ethics/Law","EULA","End-User License Agreement — a legally ENFORCEABLE contract between software publisher and user, not just a suggestion."],
 ["Ethics/Law","Copyright","The exclusive legal right given to creators over their own original works."],
 ["Ethics/Law","Social Security Act","Provides benefits for the elderly, blind, disabled, and unemployed. Funded by worker/employer taxes."],
 ["Ethics/Law","Unemployment Insurance (UI)","Benefits for workers laid off involuntarily for reasons out of their control. Funded by employer taxes. Different from severance (paid by the company)."],
 ["Career","Elevator Pitch","A 30–60 second concise, persuasive overview designed to generate interest in a person, idea, or product."],
 ["Career","Follow-Up Letter","Sent after a job interview to thank the interviewer — a standard professional practice."],
 ["Career","SPOC","Single Point of Contact — a designated person responsible for all communications on a specific client, project, or task."],
 ["Career","Micro-credentials","Short, stackable programs teaching specific skills (e.g., Coursera), usually awarding a digital badge/certificate."],
];

var STUDY_QUESTIONS = [
 {cat:"Comm/Docs", q:"What is the key difference between a memo and a letter?",
  opts:["A memo is internal; a letter is external","A memo is external; a letter is internal","A memo is handwritten; a letter is typed","There is no difference"],
  a:0, why:"Memos = INTERNAL communication within an organization. Letters = EXTERNAL communication."},
 {cat:"Comm/Docs", q:"In block format, how are all the lines aligned?",
  opts:["Centered","Right-aligned","Left-aligned (flush left)","Indented first line"],
  a:2, why:"Block format = all text left-aligned, single-spaced paragraphs, double space between them, no indentation."},
 {cat:"Comm/Docs", q:"What is the official written record of what was discussed and decided at a meeting?",
  opts:["The agenda","The minutes","The memo","The itinerary"],
  a:1, why:"Minutes are the official record (attendees, date, agenda, decisions, action items). The agenda is the list of topics planned beforehand."},
 {cat:"Mail", q:"Which mail service is the FASTEST?",
  opts:["First-Class Mail","Priority Mail","Express Mail","Parcel Post"],
  a:2, why:"Speed ranking: Express (1 day) > Priority (1–3) > First-Class (1–5) > Parcel Post (2–8)."},
 {cat:"Mail", q:"You need to send a large, heavy, non-letter package as cheaply as possible. Which USPS service fits best?",
  opts:["Express Mail","Parcel Post","Certified Mail","Registered Mail"],
  a:1, why:"Parcel Post is for large, heavy, non-letter packages — the cheapest option for heavy items (2–8 days)."},
 {cat:"Mail", q:"You must mail a legal document and need proof it was delivered (a signature). Which service?",
  opts:["First-Class Mail","Certified Mail","Parcel Post","Express Mail"],
  a:1, why:"Certified Mail provides proof of mailing and delivery confirmation (signature) — used for legal documents. Same speed as First-Class."},
 {cat:"Mail", q:"Which USPS service offers MAXIMUM security and is used for valuables?",
  opts:["Priority Mail","Registered Mail","First-Class Mail","Parcel Post"],
  a:1, why:"Registered Mail is tracked at every step and insured — maximum security, used for valuables."},
 {cat:"Ownership", q:"A small business wants LIMITED LIABILITY with PASS-THROUGH taxation. Which structure fits best?",
  opts:["Sole Proprietorship","General Partnership","LLC","C Corporation"],
  a:2, why:"An LLC gives limited liability protection while passing profits/losses through to owners' personal taxes."},
 {cat:"Ownership", q:"Which statement is TRUE of a sole proprietorship?",
  opts:["It is a separate legal entity from its owner","The owner has unlimited personal liability","It can easily sell stock to raise capital","It faces double taxation"],
  a:1, why:"In a sole proprietorship the owner and business are legally one and the same — unlimited personal liability."},
 {cat:"Ownership", q:"What is the main drawback of a C Corporation?",
  opts:["Unlimited personal liability","It cannot raise capital","Double taxation","Owner and business assets are the same"],
  a:2, why:"A C Corp pays corporate income tax, then shareholders pay tax on dividends — double taxation. An S Corp avoids this."},
 {cat:"Finance", q:"The balance sheet equation is:",
  opts:["Assets = Liabilities + Owner's Equity","Assets = Revenue − Expenses","Revenue = Assets + Liabilities","Net Income = Assets − Equity"],
  a:0, why:"Assets = Liabilities + Owner's Equity — the balance sheet always balances."},
 {cat:"Finance", q:"Net Income is calculated as:",
  opts:["Revenue − Cost of Goods Sold","Revenue − All Expenses","Assets − Liabilities","Current Assets − Current Liabilities"],
  a:1, why:"Net Income = Revenue − ALL Expenses (the bottom line). Revenue − COGS is Gross Profit."},
 {cat:"Finance", q:"Which three documents make up a 'three-way match' before paying a vendor?",
  opts:["Invoice, receipt, check","Purchase Order, Receiving Report, Vendor Invoice","Budget, ledger, journal","Requisition, voucher, W-2"],
  a:1, why:"Three-way match = Purchase Order + Receiving Report + Vendor Invoice, all confirmed before authorizing payment."},
 {cat:"Finance", q:"A petty cash reconciliation shows receipts are short by $7. What is the correct action?",
  opts:["Ignore it since it's small","Record the $7 as a shortage (cash short/over) and replenish the fund","Take $7 from your own wallet quietly","Close the petty cash fund permanently"],
  a:1, why:"Mark the overage/shortage at period end, then replenish the imprest fund back to its original amount — keep the paper trail."},
 {cat:"Finance", q:"In an imprest petty cash system, after you spend money the fund is:",
  opts:["Left at the lower balance","Replenished back to its original fixed amount","Doubled for next month","Converted to a checking account"],
  a:1, why:"An imprest system keeps a FIXED amount — you replenish exactly what was spent to return to the original total."},
 {cat:"Finance", q:"Which INTERNAL document requests permission to buy something BEFORE a Purchase Order is issued?",
  opts:["Voucher","Purchase requisition","Invoice","Receiving report"],
  a:1, why:"A purchase requisition is the internal request that goes to purchasing for approval before a PO is created."},
 {cat:"Finance", q:"Which document authorizes payment to a vendor AFTER confirming goods/services were received?",
  opts:["Purchase requisition","Voucher","Agenda","Journal entry"],
  a:1, why:"A voucher authorizes payment to a vendor once goods/services are confirmed received."},
 {cat:"Technology", q:"What does a router do (vs. a modem)?",
  opts:["Connects your home to the internet via an ISP","Connects devices within a local network (LAN)","Stores backup files","Scans documents into text"],
  a:1, why:"A router connects devices to each other within a LAN; a MODEM connects the home/office to the internet via an ISP."},
 {cat:"Technology", q:"In a database table, a primary key must:",
  opts:["Be unique and cannot be null","Always be null","Link to many other tables","Contain only text"],
  a:0, why:"A primary key uniquely identifies each record — it cannot be null and has no duplicates. Foreign keys link tables and can be null."},
 {cat:"Technology", q:"Which file format best preserves layout and fonts across all devices?",
  opts:[".TXT",".DOCX",".PDF",".CSV"],
  a:2, why:"PDF preserves layout and embeds fonts so it looks identical everywhere — best for a final, fixed document."},
 {cat:"Technology", q:"Which file format supports TRANSPARENT backgrounds and is best for logos and graphics?",
  opts:[".JPG",".PNG",".CSV",".TXT"],
  a:1, why:"PNG supports transparency and sharp edges — ideal for logos/graphics. JPG is compressed, best for photos."},
 {cat:"Technology", q:"In Excel, which function key opens the 'Save As' dialog box?",
  opts:["F2","F5","F9","F12"],
  a:3, why:"F12 = Save As. (F2 enters the cell, F4 toggles absolute reference, F7 is spellcheck.)"},
 {cat:"Technology", q:"In Excel, which function key changes a cell reference to ABSOLUTE (e.g., $E$2)?",
  opts:["F2","F4","F7","F11"],
  a:1, why:"F4 toggles absolute reference ($). Absolute references stay fixed when you copy/drag a formula."},
 {cat:"Technology", q:"In a SQL SELECT query, which keyword FILTERS rows to those meeting a condition?",
  opts:["FROM","ORDER BY","WHERE","SELECT"],
  a:2, why:"WHERE filters rows by criteria. SELECT picks columns, FROM names the table, ORDER BY sorts the results."},
 {cat:"Operations", q:"Your printer shows repeated paper jams. What is the FIRST troubleshooting step?",
  opts:["Replace every internal module preemptively","Clear the paper path (and remove any torn scraps)","Buy a new printer","Call the manufacturer for a refund"],
  a:1, why:"Start with the least invasive fix: clear the paper path first; torn scraps under rollers can trigger false jam sensors."},
 {cat:"Operations", q:"For print/reprographics, at what minimum resolution should images generally be submitted?",
  opts:["72 DPI","150 DPI","300 DPI","30 DPI"],
  a:2, why:"Submit images at 300 DPI or higher for print; CMYK is the standard color mode for printing."},
 {cat:"Operations", q:"What does ergonomics fix in a workstation showing wrist pain, a low monitor, and dangling feet?",
  opts:["Raise the monitor to eye level, support wrists neutral, get feet flat on the floor","Buy a faster computer","Lower the lighting","Add a second monitor"],
  a:0, why:"Ergonomics: monitor top at/just below eye level, wrists in line with forearms, feet flat — everything supported and straight."},
 {cat:"Operations", q:"What is the FIRST step when handling a difficult/upset customer?",
  opts:["Offer a refund immediately","Paraphrase their concern to confirm understanding (active listening)","Transfer them to a manager","End the call politely"],
  a:1, why:"Active listening first — paraphrase the customer's concern to confirm you understand before solving."},
 {cat:"Records", q:"Which best describes a tickler file?",
  opts:["A list of employee complaints","A date-based reminder system (31 daily + 12 monthly folders)","A backup of the company server","A type of business letter"],
  a:1, why:"A tickler file uses 31 daily + 12 monthly folders to 'tickle' your memory about upcoming deadlines."},
 {cat:"Records", q:"When purging records, what should you do FIRST?",
  opts:["Shred everything immediately","Check the retention schedule and confirm no legal hold applies","Email customers for permission","Archive everything to the cloud"],
  a:1, why:"Always verify the retention schedule and that no litigation/legal hold applies before destroying any records."},
 {cat:"Records", q:"When a custom policy says keep records 3 years but the default schedule says 7 years, you keep them for:",
  opts:["3 years","7 years (the longest applicable period)","5 years (the average)","Forever"],
  a:1, why:"Default to the LONGEST applicable retention period — so 7 years here."},
 {cat:"Records", q:"Under ARMA rules, how is the business name 'The Coffee Shop' indexed (filed)?",
  opts:["Under T for 'The'","Under C — 'The' is dropped (or moved to the end)","Under S for 'Shop'","It cannot be filed alphabetically"],
  a:1, why:"Businesses are filed as written, but a leading 'The' is omitted (or filed last) — so it indexes under 'Coffee Shop'."},
 {cat:"Records", q:"What is the FIRST of the five steps of filing?",
  opts:["Coding","Sorting","Inspecting","Storing"],
  a:2, why:"Order: Inspecting → Indexing → Coding → Sorting → Storing. Inspecting checks the doc is released/ready to file."},
 {cat:"Ethics/Law", q:"Which statement about EULAs (End-User License Agreements) is most accurate?",
  opts:["They are suggestions, not enforceable","They are legally enforceable contracts","They only apply to free software","They expire after one use"],
  a:1, why:"A EULA is a legally enforceable contract between the software publisher and the user — not just a suggestion."},
 {cat:"Ethics/Law", q:"Confidentiality in an office primarily means:",
  opts:["Sharing information freely with coworkers","Protecting sensitive information from unauthorized access","Keeping the office quiet","Backing up files daily"],
  a:1, why:"Confidentiality = protecting sensitive information from unauthorized access (lock screens, secure docs, follow privacy policy)."},
 {cat:"Ethics/Law", q:"Sarbanes-Oxley (SOX) primarily aims to:",
  opts:["Protect investors through corporate financial accountability","Set the federal minimum wage","Protect employees with disabilities","Regulate the mail system"],
  a:0, why:"SOX requires CEOs/CFOs to approve financials, mandates audits, and protects whistleblowers — all to protect investors."},
 {cat:"Ethics/Law", q:"The ADA requires employers to provide accommodations when they have at least how many employees?",
  opts:["5","10","15","50"],
  a:2, why:"The ADA generally applies to employers with 15 or more employees."},
 {cat:"Ethics/Law", q:"The FLSA (Fair Labor Standards Act) mandates overtime pay at what rate, and after how many hours?",
  opts:["2× pay after 35 hours/week","1.5× pay after 40 hours/week","1.25× pay after 45 hours/week","Same rate, no overtime required"],
  a:1, why:"FLSA mandates 1.5× the regular rate for hours worked beyond 40 in a week, plus minimum wage and recordkeeping rules."},
 {cat:"Ethics/Law", q:"HIPAA protects which type of information from disclosure without consent?",
  opts:["Financial records","Health information","Employee performance reviews","Trade secrets"],
  a:1, why:"HIPAA protects specific health information from being disclosed without patient consent."},
 {cat:"Management", q:"The 4 functions of management (POLC) are:",
  opts:["Plan, Order, Lead, Calculate","Planning, Organizing, Leading, Controlling","Produce, Operate, Launch, Close","People, Operations, Logistics, Capital"],
  a:1, why:"POLC = Planning, Organizing, Leading/Directing, Controlling."},
 {cat:"Management", q:"A 'hands-off' leader who gives skilled employees autonomy with minimal supervision uses which style?",
  opts:["Autocratic","Democratic","Laissez-faire","Transactional"],
  a:2, why:"Laissez-faire (delegative) leadership is hands-off — best with highly skilled, self-motivated teams."},
 {cat:"Management", q:"On an organizational chart, a DASHED line usually represents:",
  opts:["The CEO","A direct chain of command","A functional/secondary reporting relationship","An empty position"],
  a:2, why:"Solid lines = direct-line authority; dashed lines = functional or secondary relationships (e.g., matrix structures)."},
 {cat:"Management", q:"What does the SMART in SMART goals stand for?",
  opts:["Simple, Modern, Accurate, Real, Tested","Specific, Measurable, Achievable, Relevant, Time-bound","Strategic, Managed, Audited, Reviewed, Tracked","Smart, Motivated, Active, Ready, Tough"],
  a:1, why:"SMART = Specific, Measurable, Achievable, Relevant, Time-bound."},
 {cat:"Management", q:"On the Eisenhower Matrix, a task that is URGENT but NOT important should be:",
  opts:["Done first","Scheduled for later","Delegated","Eliminated"],
  a:2, why:"Urgent + Important = Do first; Important + not urgent = Schedule; Urgent + not important = Delegate; Neither = Eliminate."},
 {cat:"Management", q:"From highest to lowest, the three levels of management are:",
  opts:["Line → Middle → Executive","Executive/Top → Middle → Line/Supervisory","Middle → Executive → Line","Supervisory → Executive → Middle"],
  a:1, why:"Top/Executive (vision/strategy) → Middle (implements strategy) → Line/Supervisory (day-to-day operations)."},
 {cat:"Economics", q:"Cartels and trusts both create monopoly power. How do they differ?",
  opts:["A cartel merges companies; a trust keeps them separate","In a cartel companies keep autonomy and can leave easily; a trust merges them under trustees and is hard to leave","They are the same thing","A trust is legal; a cartel is always illegal"],
  a:1, why:"Cartel = colluding but autonomous companies (easy to leave). Trust = companies merged under trustees (hard to leave)."},
 {cat:"Economics", q:"GDP (Gross Domestic Product) measures:",
  opts:["A company's yearly profit","The total market value of all goods and services produced in a country in a period","The national unemployment rate","The amount of money the government prints"],
  a:1, why:"GDP = total market value of all goods/services produced within a country in a given time period."},
 {cat:"Economics", q:"In which economic system does the GOVERNMENT own the means of production?",
  opts:["Capitalism","Socialism","Free market","Monopolistic competition"],
  a:1, why:"Socialism = government owns the means of production. Capitalism = private individuals own most businesses."},
 {cat:"Economics", q:"Capitalism is best defined as an economic system where:",
  opts:["The state directs all production","Private individuals own and operate most businesses","No one is allowed to own property","Prices are fixed by the government"],
  a:1, why:"Capitalism = private individuals own and operate the majority of businesses that provide goods/services."},
 {cat:"Career", q:"How long should an elevator pitch last?",
  opts:["5–10 seconds","30–60 seconds","3–5 minutes","10 minutes"],
  a:1, why:"An elevator pitch is a 30–60 second concise, persuasive overview designed to generate interest."},
 {cat:"Career", q:"What is the standard professional practice to do AFTER a job interview?",
  opts:["Call the company daily until you hear back","Send a follow-up (thank-you) letter","Post about it on social media","Nothing — just wait"],
  a:1, why:"Sending a follow-up letter thanking the interviewer is standard professional etiquette."},
 {cat:"Career", q:"When resigning from a position, what is the typical amount of notice given?",
  opts:["Same day","One week","Two weeks","Three months"],
  a:2, why:"Standard resignation practice: give about two weeks' notice, submit a formal letter, and complete transition tasks professionally."},
 {cat:"Math", q:"A store's monthly sales rose from 200 units to 250 units. What is the percent change?",
  opts:["20%","25%","50%","80%"],
  a:1, why:"Percent change = (New − Old) ÷ Old = (250 − 200) ÷ 200 = 50 ÷ 200 = 25%."},
 {cat:"Math", q:"An employee works 45 hours at $20/hour with overtime (1.5×) after 40 hours. What is gross pay?",
  opts:["$900","$950","$1,000","$1,350"],
  a:1, why:"Regular: 40 × $20 = $800. Overtime: 5 × ($20 × 1.5 = $30) = $150. Total = $950."},
 {cat:"Math", q:"An item priced at $120 is marked 25% off. What is the sale price?",
  opts:["$30","$90","$95","$96"],
  a:1, why:"Sale price = Original × (1 − discount) = $120 × 0.75 = $90."},
 {cat:"Math", q:"Fixed costs are $1,000, selling price is $25/unit, and variable cost is $15/unit. What is the break-even point?",
  opts:["40 units","100 units","400 units","1,000 units"],
  a:1, why:"Break-even = Fixed Costs ÷ (Price − Variable Cost) = 1,000 ÷ (25 − 15) = 1,000 ÷ 10 = 100 units."},
 {cat:"Math", q:"Net income is $20,000 and revenue is $100,000. What is the profit margin?",
  opts:["5%","20%","80%","200%"],
  a:1, why:"Profit Margin = (Net Income ÷ Revenue) × 100 = (20,000 ÷ 100,000) × 100 = 20%."},
 {cat:"Math", q:"Revenue is $50,000 and Cost of Goods Sold is $30,000. What is the gross profit?",
  opts:["$15,000","$20,000","$30,000","$80,000"],
  a:1, why:"Gross Profit = Revenue − COGS = $50,000 − $30,000 = $20,000."},
 {cat:"Math", q:"Current assets are $40,000 and current liabilities are $25,000. What is the working capital?",
  opts:["$15,000","$25,000","$40,000","$65,000"],
  a:0, why:"Working Capital = Current Assets − Current Liabilities = $40,000 − $25,000 = $15,000."},
 {cat:"Math", q:"You invest $10,000 and it returns $12,000. What is the ROI?",
  opts:["12%","20%","83%","120%"],
  a:1, why:"ROI = (Gain − Cost) ÷ Cost × 100 = (12,000 − 10,000) ÷ 10,000 × 100 = 20%."},
 {cat:"Math", q:"An employee works 32 hours at $18/hour (no overtime). What is the pay?",
  opts:["$512","$576","$640","$320"],
  a:1, why:"Hourly Pay = Hours × Rate = 32 × $18 = $576."},
 {cat:"Math", q:"Revenue is $80,000 and total expenses are $55,000. What is net income?",
  opts:["$25,000","$35,000","$55,000","$135,000"],
  a:0, why:"Net Income = Revenue − All Expenses = $80,000 − $55,000 = $25,000."},
];
